# Generated by Django 4.2.3 on 2023-08-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailuser',
            old_name='mall_code',
            new_name='mall_id',
        ),
        migrations.RenameField(
            model_name='retailuser',
            old_name='shop_code',
            new_name='shop_id',
        ),
    ]
