# Generated by Django 4.2.3 on 2023-08-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='vehicle',
            field=models.CharField(default='MH28AB1234', max_length=15),
            preserve_default=False,
        ),
    ]
